# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: laundry_monitor
    ports:
      - "5432:5432"

  flyway:
    container_name: flyway
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/laundry_monitor -schemas=public -user=root -password=password -connectRetries=60 migrate
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - db
